// <auto-generated />
using System;
using AirBB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBnbContext))]
    partial class AirBnbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AirBB.Models.Client", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Boston"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Miami"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            ReservationEndDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 101
                        });
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 101,
                            BathroomNumber = 1,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            PricePerNight = 189m,
                            ResidencePicture = "chi_loop.jpg"
                        },
                        new
                        {
                            ResidenceId = 102,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 3,
                            LocationId = 1,
                            Name = "Lincoln Park Flat",
                            PricePerNight = 139m,
                            ResidencePicture = "chi_lincoln.jpg"
                        },
                        new
                        {
                            ResidenceId = 201,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 2,
                            LocationId = 2,
                            Name = "NYC Soho Loft",
                            PricePerNight = 259m,
                            ResidencePicture = "nyc_soho.jpg"
                        },
                        new
                        {
                            ResidenceId = 301,
                            BathroomNumber = 2,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = 3,
                            Name = "Boston Back Bay Condo",
                            PricePerNight = 209m,
                            ResidencePicture = "bos_backbay.jpg"
                        },
                        new
                        {
                            ResidenceId = 401,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 6,
                            LocationId = 4,
                            Name = "Miami Beach House",
                            PricePerNight = 299m,
                            ResidencePicture = "mia_beach.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.HasOne("AirBB.Models.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
